In [2]:
from array import array

array.array

In [3]:
array('i')

array('i')

In [4]:
my_array = array('i', [1, 2, 3, 4, 5])
my_array

array('i', [1, 2, 3, 4, 5])

In [2]:
import numpy as np

np_array = np.array([1, 2, 3, 4, 5])
np_array

array([1, 2, 3, 4, 5])

In [7]:
def linear_search(arr, item):
    for i,j in enumerate(arr):
        if j == item:
            return i
    return -1

In [9]:
my_array = np.array([1,2,3,4,5,6])

linear_search(my_array, 10)

-1

In [11]:
import time
import array
import numpy as np

# Initialize variables
size = 10**7

# 1. Time creation of a list
list_time_start = time.time()
my_list = [i for i in range(size)]
list_time_end = time.time()

# 2. Time creation of a Python array
array_time_start = time.time()
my_array = array.array('i', (i for i in range(size)))  # 'i' for integer
array_time_end = time.time()

# 3. Time creation of a NumPy array
numpy_time_start = time.time()
my_numpy_array = np.arange(size)
numpy_time_end = time.time()

# Print the results
list_time = list_time_end - list_time_start
array_time = array_time_end - array_time_start
numpy_time = numpy_time_end - numpy_time_start

print(f"Time taken to create list: {list_time:.6f} seconds")
print(f"Time taken to create Python array: {array_time:.6f} seconds")
print(f"Time taken to create NumPy array: {numpy_time:.6f} seconds")


Time taken to create list: 0.156240 seconds
Time taken to create Python array: 0.511110 seconds
Time taken to create NumPy array: 0.012349 seconds


In [12]:
## INSERTING AT START COMPARISON

import time
import array
import numpy as np

# Initialize variables
size = 10**5  # Reduced size due to inefficiency of inserting at the start

# 1. Time insertion at the start of a list
list_time_start = time.time()
my_list = []
for i in range(size):
    my_list.insert(0, i)  # Insert at the start
list_time_end = time.time()

# 2. Time insertion at the start of a Python array
array_time_start = time.time()
my_array = array.array('i')
for i in range(size):
    my_array.insert(0, i)  # Insert at the start
array_time_end = time.time()

# 3. Time insertion at the start of a NumPy array
numpy_time_start = time.time()
my_numpy_array = np.array([], dtype=int)
for i in range(size):
    my_numpy_array = np.insert(my_numpy_array, 0, i)  # Insert at the start
numpy_time_end = time.time()

# Print the results
list_time = list_time_end - list_time_start
array_time = array_time_end - array_time_start
numpy_time = numpy_time_end - numpy_time_start

print(f"Time taken to insert at start of list: {list_time:.6f} seconds")
print(f"Time taken to insert at start of Python array: {array_time:.6f} seconds")
print(f"Time taken to insert at start of NumPy array: {numpy_time:.6f} seconds")


Time taken to insert at start of list: 2.472689 seconds
Time taken to insert at start of Python array: 0.395879 seconds
Time taken to insert at start of NumPy array: 1.438120 seconds


In [13]:
import time
import numpy as np

# Initialize variables
size = 10**6
my_list = list(range(size))
my_numpy_array = np.arange(size)

# 1. Time iteration over list using enumerate
list_enum_time_start = time.time()
for idx, value in enumerate(my_list):
    pass
list_enum_time_end = time.time()

# 2. Time iteration over list using range(len)
list_range_time_start = time.time()
for idx in range(len(my_list)):
    value = my_list[idx]
    pass
list_range_time_end = time.time()

# 3. Time iteration over NumPy array using enumerate
numpy_enum_time_start = time.time()
for idx, value in enumerate(my_numpy_array):
    pass
numpy_enum_time_end = time.time()

# 4. Time iteration over NumPy array using range(len)
numpy_range_time_start = time.time()
for idx in range(len(my_numpy_array)):
    value = my_numpy_array[idx]
    pass
numpy_range_time_end = time.time()

# Print the results
list_enum_time = list_enum_time_end - list_enum_time_start
list_range_time = list_range_time_end - list_range_time_start
numpy_enum_time = numpy_enum_time_end - numpy_enum_time_start
numpy_range_time = numpy_range_time_end - numpy_range_time_start

print(f"Time taken to iterate over list with enumerate: {list_enum_time:.6f} seconds")
print(f"Time taken to iterate over list with range(len): {list_range_time:.6f} seconds")
print(f"Time taken to iterate over NumPy array with enumerate: {numpy_enum_time:.6f} seconds")
print(f"Time taken to iterate over NumPy array with range(len): {numpy_range_time:.6f} seconds")


Time taken to iterate over list with enumerate: 0.051578 seconds
Time taken to iterate over list with range(len): 0.042723 seconds
Time taken to iterate over NumPy array with enumerate: 0.049307 seconds
Time taken to iterate over NumPy array with range(len): 0.068565 seconds


In [1]:
# Create two dimensional array
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twoDArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
# Adding Columns to a 2D NumPy Array
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newColumn = np.array([[10], [11], [12]])
new2DArray = np.append(twoDArray, newColumn, axis=1)
print(new2DArray)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


The np.append function needs to iterate over all elements in both arrays to create a new array. If twoDArray has m rows and n columns, the time complexity for this operation is O(m * n).

In [3]:
# Adding Columns at the Start of a 2D NumPy Array
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newColumn = np.array([[10], [11], [12]])
new2DArray = np.append(newColumn, twoDArray, axis=1)
print(new2DArray)


[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]]


In [4]:
# Adding Rows to a 2D NumPy Array
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newRow = np.array([[10, 11, 12]])
new2DArray = np.append(twoDArray, newRow, axis=0)
print(new2DArray)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
# use insert function to add a row at the start of a 2D NumPy array
import numpy as np

twoDArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newRow = np.array([[10, 11, 12]])
new2DArray = np.insert(twoDArray, 2, newRow, axis=0)
print(new2DArray)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [ 7  8  9]]


In [13]:
# accessing elements in a 2D NumPy array
import numpy as np

twoDArray = np.array([[1, 2, 3, 4], [5, 6, 7,8], [9, 10, 11, 12]])
print(twoDArray)
print(twoDArray[0, 0], twoDArray[0, 1], twoDArray[0, 2], twoDArray[0, 3])
print(twoDArray[1, 0], twoDArray[1, 1], twoDArray[1, 2], twoDArray[1, 3])
print(twoDArray[2, 0], twoDArray[2, 1], twoDArray[2, 2], twoDArray[2, 3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1 2 3 4
5 6 7 8
9 10 11 12
